#!/sbin/busybox sh

# $1 - "boeffla_master"
# $2 - value=
# Created By Dorimanx

BB=/sbin/busybox

if [ "a$2" != "a" ]; then
	boeffla_master=$2;

if [ ! -e /data/.gabriel/boeffla_speaker ]; then
	touch /data/.gabriel/boeffla_speaker;
fi;

if [ ! -e /data/.gabriel/boeffla_headphone_l ] || [ ! -e /data/.gabriel/boeffla_headphone_r ]; then
	touch /data/.gabriel/boeffla_headphone_l;
	touch /data/.gabriel/boeffla_headphone_r;
fi;

SPEAKER=`cat /data/.gabriel/boeffla_speaker`;
HEADPHONE_L=`cat /data/.gabriel/boeffla_headphone_l`;
HEADPHONE_R=`cat /data/.gabriel/boeffla_headphone_r`;

	case "${boeffla_master}" in
		on)
			echo 1 > /sys/class/misc/boeffla_sound/boeffla_sound;
			(
				echo "$SPEAKER"" ""$SPEAKER" > /sys/class/misc/boeffla_sound/speaker_volume;
				echo "$HEADPHONE_L"" ""$HEADPHONE_R" > /sys/class/misc/boeffla_sound/headphone_volume;
			)&
		;;
		off)
			echo 0 > /sys/class/misc/boeffla_sound/boeffla_sound;
		;;
		*)
			boeffla_master=off;
		;;
	esac;
fi;

echo ${boeffla_master};
