#!/sbin/busybox sh

# $1 - "cpu_undervolt"
# $2 - value=
# Created By Dorimanx

BB=/sbin/busybox

# get values from profile
PROFILE=$(cat /data/.gabriel/.active.profile);
. /data/.gabriel/"$PROFILE".profile;

if [ "a$2" != "a" ]; then
	cpu_undervolt=$2;

	case "${cpu_undervolt}" in
		0)
			if [ -f /sys/devices/system/cpu/cpu0/cpufreq/UV_mV_table ]; then
				echo "800 800 800 800 810 820 830 850 860 890 900 925 970 1030 1065" > /sys/devices/system/cpu/cpu0/cpufreq/UV_mV_table
			fi;
		;;
		10)
			if [ -f /sys/devices/system/cpu/cpu0/cpufreq/UV_mV_table ]; then
				echo "790 790 790 790 800 810 820 840 850 880 890 915 960 1020 1055" > /sys/devices/system/cpu/cpu0/cpufreq/UV_mV_table
			fi;
		;;
		20)
			if [ -f /sys/devices/system/cpu/cpu0/cpufreq/UV_mV_table ]; then
				echo "780 780 780 780 790 800 810 830 840 870 880 905 950 1010 1045" > /sys/devices/system/cpu/cpu0/cpufreq/UV_mV_table
			fi;
		;;
		30)
			if [ -f /sys/devices/system/cpu/cpu0/cpufreq/UV_mV_table ]; then
				echo "770 770 770 770 780 790 800 820 830 860 870 895 940 1000 1035" > /sys/devices/system/cpu/cpu0/cpufreq/UV_mV_table
			fi;
		;;
		40)
			if [ -f /sys/devices/system/cpu/cpu0/cpufreq/UV_mV_table ]; then
				echo "760 760 760 760 770 780 790 810 820 850 860 885 930 990 1025" > /sys/devices/system/cpu/cpu0/cpufreq/UV_mV_table
			fi;
		;;
		50)
			if [ -f /sys/devices/system/cpu/cpu0/cpufreq/UV_mV_table ]; then
				echo "750 750 750 750 760 770 780 800 810 840 850 875 920 980 1015" > /sys/devices/system/cpu/cpu0/cpufreq/UV_mV_table
			fi;
		;;
		60)
			if [ -f /sys/devices/system/cpu/cpu0/cpufreq/UV_mV_table ]; then
				echo "740 740 740 740 750 760 770 790 800 830 840 865 910 970 1005" > /sys/devices/system/cpu/cpu0/cpufreq/UV_mV_table
			fi;
		;;
		70)
			if [ -f /sys/devices/system/cpu/cpu0/cpufreq/UV_mV_table ]; then
				echo "730 730 730 730 740 750 760 780 790 820 830 855 900 960 995" > /sys/devices/system/cpu/cpu0/cpufreq/UV_mV_table
			fi;
		;;
		gabriel_light)
			if [ -f /sys/devices/system/cpu/cpu0/cpufreq/UV_mV_table ]; then
				echo "770 770 770 770 780 795 805 825 835 870 880 905 950 1010 1045" > /sys/devices/system/cpu/cpu0/cpufreq/UV_mV_table
			fi;
		;;
		gabriel_hard)
			if [ -f /sys/devices/system/cpu/cpu0/cpufreq/UV_mV_table ]; then
				echo "760 760 760 760 770 790 800 820 830 865 875 900 945 1005 1040" > /sys/devices/system/cpu/cpu0/cpufreq/UV_mV_table
			fi;
		;;
		*)
			cpu_undervolt=msm_hotplug;
		;;
	esac;
fi;

echo ${cpu_undervolt};
