#!/sbin/busybox sh

# $1 - "default_cpu0_gov"
# $2 - value=
# Created By Dorimanx

# get values from profile
PROFILE=$(cat /data/.gabriel/.active.profile);
. /data/.gabriel/"$PROFILE".profile;

if [ "a$2" != "a" ]; then
	default_cpu0_gov=$2;

	echo "$default_cpu0_gov" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor;
	sleep 2;
	echo "$cpu_zzmoove_profile" > /sys/devices/system/cpu/cpufreq/zzmoove/profile_number;
	sleep 2;
	echo "$min_online_cpus" > /sys/devices/system/cpu/cpufreq/zzmoove/hotplug_min_limit;
	echo "$eco_mode" > /sys/devices/system/cpu/cpufreq/zzmoove/hotplug_max_limit;
	if [ -e /res/uci_boot.sh ]; then
		/res/uci_boot.sh power_mode $power_mode > /dev/null;
	else
		/res/uci.sh power_mode $power_mode > /dev/null;
	fi;
fi;

echo ${default_cpu0_gov};
