#!/sbin/busybox sh

# $1 - "hotplug"
# $2 - value=
# Created By Dorimanx

BB=/sbin/busybox

# get values from profile
PROFILE=$(cat /data/.gabriel/.active.profile);
. /data/.gabriel/"$PROFILE".profile;

if [ "$(pgrep -f "/system/bin/thermal-engine" | wc -l)" -eq "1" ]; then
	$BB renice -n -20 -p "$(pgrep -f "/system/bin/thermal-engine")";
fi;

if [ "a$2" != "a" ]; then
	hotplug=$2;

	case "${hotplug}" in
		intelli)
			echo "0" > /sys/kernel/alucard_hotplug/hotplug_enable;
			echo "0" > /sys/module/msm_hotplug/msm_enabled;
			echo "0" > /sys/devices/system/cpu/cpu0/rq-stats/hotplug_enable;
			echo "0" > /sys/kernel/thunderplug/hotplug_enabled;
			echo "0" > /sys/devices/system/cpu/cpu0/rq-stats/bricked_hotplug_enable;
			echo "0" > /sys/kernel/msm_mpdecision/conf/enabled;
			echo "1" > /sys/devices/system/cpu/cpufreq/zzmoove/disable_hotplug;
			(
				sleep 2;
				echo "1" > /sys/kernel/intelli_plug/intelli_plug_active;
				echo "$min_online_cpus" > /sys/kernel/intelli_plug/min_cpus_online;
				if [ -e /res/uci_boot.sh ]; then
					$BB sh /res/uci_boot.sh eco_mode "$eco_mode";
				else
					$BB sh /res/uci.sh eco_mode "$eco_mode";
				fi;
			)&
		;;
		msm_hotplug)
			echo "0" > /sys/kernel/intelli_plug/intelli_plug_active;
			echo "0" > /sys/kernel/alucard_hotplug/hotplug_enable;
			echo "0" > /sys/devices/system/cpu/cpu0/rq-stats/hotplug_enable;
			echo "0" > /sys/kernel/thunderplug/hotplug_enabled;
			echo "0" > /sys/devices/system/cpu/cpu0/rq-stats/bricked_hotplug_enable;
			echo "0" > /sys/kernel/msm_mpdecision/conf/enabled;
			echo "1" > /sys/devices/system/cpu/cpufreq/zzmoove/disable_hotplug;
			(
				sleep 2;
				echo "1" > /sys/module/msm_hotplug/msm_enabled;
				echo "$min_online_cpus" > /sys/module/msm_hotplug/min_cpus_online;
				if [ -e /res/uci_boot.sh ]; then
					$BB sh /res/uci_boot.sh eco_mode "$eco_mode";
				else
					$BB sh /res/uci.sh eco_mode "$eco_mode";
				fi;
			)&
		;;
		alucard)
			echo "0" > /sys/kernel/intelli_plug/intelli_plug_active;
			echo "0" > /sys/module/msm_hotplug/msm_enabled;
			echo "0" > /sys/devices/system/cpu/cpu0/rq-stats/hotplug_enable;
			echo "0" > /sys/kernel/thunderplug/hotplug_enabled;
			echo "0" > /sys/devices/system/cpu/cpu0/rq-stats/bricked_hotplug_enable;
			echo "0" > /sys/kernel/msm_mpdecision/conf/enabled;
			echo "1" > /sys/devices/system/cpu/cpufreq/zzmoove/disable_hotplug;
			(
				sleep 2;
				echo "1" > /sys/kernel/alucard_hotplug/hotplug_enable;
				echo "$min_online_cpus" > /sys/kernel/alucard_hotplug/min_cpus_online;
				if [ -e /res/uci_boot.sh ]; then
					$BB sh /res/uci_boot.sh eco_mode "$eco_mode";
				else
					$BB sh /res/uci.sh eco_mode "$eco_mode";
				fi;
			)&
		;;
		thunderplug)
			echo "0" > /sys/kernel/intelli_plug/intelli_plug_active;
			echo "0" > /sys/kernel/alucard_hotplug/hotplug_enable;
			echo "0" > /sys/devices/system/cpu/cpu0/rq-stats/hotplug_enable;
			echo "0" > /sys/module/msm_hotplug/msm_enabled;
			echo "0" > /sys/devices/system/cpu/cpu0/rq-stats/bricked_hotplug_enable;
			echo "0" > /sys/kernel/msm_mpdecision/conf/enabled;
			echo "1" > /sys/devices/system/cpu/cpufreq/zzmoove/disable_hotplug;
			(
				sleep 2;
				echo "1" > /sys/kernel/thunderplug/hotplug_enabled;
				echo "$min_online_cpus" > /sys/kernel/thunderplug/min_core_online;
				if [ -e /res/uci_boot.sh ]; then
					$BB sh /res/uci_boot.sh eco_mode "$eco_mode";
				else
					$BB sh /res/uci.sh eco_mode "$eco_mode";
				fi;
			)&
		;;
		bricked)
			echo "0" > /sys/kernel/intelli_plug/intelli_plug_active;
			echo "0" > /sys/kernel/alucard_hotplug/hotplug_enable;
			echo "0" > /sys/devices/system/cpu/cpu0/rq-stats/hotplug_enable;
			echo "0" > /sys/module/msm_hotplug/msm_enabled;
			echo "0" > /sys/kernel/thunderplug/hotplug_enabled;
			echo "1" > /sys/devices/system/cpu/cpufreq/zzmoove/disable_hotplug;
			(
				sleep 2;
				echo "1" > /sys/devices/system/cpu/cpu0/rq-stats/bricked_hotplug_enable;
				sleep 2;
				echo "1" > /sys/kernel/msm_mpdecision/conf/enabled;
				echo "$min_online_cpus" > /sys/kernel/msm_mpdecision/conf/min_cpus_online;
				if [ -e /res/uci_boot.sh ]; then
					$BB sh /res/uci_boot.sh eco_mode "$eco_mode";
				else
					$BB sh /res/uci.sh eco_mode "$eco_mode";
				fi;
			)&
		;;
		zzmoove)
			echo "0" > /sys/kernel/intelli_plug/intelli_plug_active;
			echo "0" > /sys/kernel/alucard_hotplug/hotplug_enable;
			echo "0" > /sys/devices/system/cpu/cpu0/rq-stats/hotplug_enable;
			echo "0" > /sys/module/msm_hotplug/msm_enabled;
			echo "0" > /sys/kernel/thunderplug/hotplug_enabled;
			echo "0" > /sys/devices/system/cpu/cpu0/rq-stats/bricked_hotplug_enable;
			echo "0" > /sys/kernel/msm_mpdecision/conf/enabled;
			(
				sleep 2;
				echo "0" > /sys/devices/system/cpu/cpufreq/zzmoove/disable_hotplug;
				sleep 1;
				echo "$min_online_cpus" > /sys/devices/system/cpu/cpufreq/zzmoove/hotplug_min_limit;
				if [ -e /res/uci_boot.sh ]; then
					$BB sh /res/uci_boot.sh eco_mode "$eco_mode";
				else
					$BB sh /res/uci.sh eco_mode "$eco_mode";
				fi;
			)&
		;;
		*)
			hotplug=msm_hotplug;
		;;
	esac;
fi;

echo ${hotplug};
