#!/sbin/busybox sh

# $1 - "intelligent_hotplug_profile"
# $2 - value=
# Created By Dorimanx

BB=/sbin/busybox

# get values from profile
PROFILE=$(cat /data/.gabriel/.active.profile);
. /data/.gabriel/"$PROFILE".profile;

if [ "a$2" != "a" ]; then
	intelligent_hotplug_profile=$2;

	case "${intelligent_hotplug_profile}" in
		balance)
			echo 0 > /sys/kernel/intelli_plug/full_mode_profile
		;;
		performance)
			echo 1 > /sys/kernel/intelli_plug/full_mode_profile
		;;
		conservative)
			echo 2 > /sys/kernel/intelli_plug/full_mode_profile
		;;
		disable)
			echo 3 > /sys/kernel/intelli_plug/full_mode_profile
		;;
		tri)
			echo 4 > /sys/kernel/intelli_plug/full_mode_profile
		;;
		eco)
			echo 5 > /sys/kernel/intelli_plug/full_mode_profile
		;;
		strict)
			echo 6 > /sys/kernel/intelli_plug/full_mode_profile
		;;
		*)
			intelligent_hotplug_profile=balance;
		;;
	esac;
fi;

echo ${intelligent_hotplug_profile};
