#!/sbin/busybox sh

# $1 - "min_online_cpus"
# $2 - value=
# Created By Dorimanx

if [ "a$2" != "a" ]; then
	min_online_cpus=$2;

	case "${min_online_cpus}" in
		1)
			echo "1" > /sys/kernel/alucard_hotplug/min_cpus_online;
			echo "1" > /sys/module/msm_hotplug/min_cpus_online;
			echo "1" > /sys/kernel/intelli_plug/min_cpus_online;
			echo "1" > /sys/kernel/msm_mpdecision/conf/min_cpus_online;
			echo "1" > /sys/devices/system/cpu/cpufreq/zzmoove/hotplug_min_limit;
		;;
		2)
			echo "2" > /sys/kernel/alucard_hotplug/min_cpus_online;
			echo "2" > /sys/module/msm_hotplug/min_cpus_online;
			echo "2" > /sys/kernel/intelli_plug/min_cpus_online;
			echo "2" > /sys/kernel/msm_mpdecision/conf/min_cpus_online;
			echo "2" > /sys/devices/system/cpu/cpufreq/zzmoove/hotplug_min_limit;
		;;
		3)
			echo "3" > /sys/kernel/alucard_hotplug/min_cpus_online;
			echo "3" > /sys/module/msm_hotplug/min_cpus_online;
			echo "3" > /sys/kernel/intelli_plug/min_cpus_online;
			echo "3" > /sys/kernel/msm_mpdecision/conf/min_cpus_online;
			echo "3" > /sys/devices/system/cpu/cpufreq/zzmoove/hotplug_min_limit;
		;;
		4)
			echo "4" > /sys/kernel/alucard_hotplug/min_cpus_online;
			echo "4" > /sys/module/msm_hotplug/min_cpus_online;
			echo "4" > /sys/kernel/intelli_plug/min_cpus_online;
			echo "4" > /sys/kernel/msm_mpdecision/conf/min_cpus_online;
			echo "4" > /sys/devices/system/cpu/cpufreq/zzmoove/hotplug_min_limit;
		;;
		*)
			min_online_cpus=1;
		;;
	esac;
fi;

echo ${min_online_cpus};
