#!/sbin/busybox sh

# $1 - "oom_config_screen_on"
# $2 - value=

if [ "a$2" == "a" ]; then
	echo $oom_config_screen_on;
else
	oom_config_screen_on=$2;
	echo "$oom_config_screen_on";
fi;

PROFILE=`cat /data/.gabriel/.active.profile`;
AUTO_OOM=`cat /data/.gabriel/${PROFILE}.profile | grep auto_oom=on | wc -l`

if [ "$AUTO_OOM" -eq "1" ]; then
	case "${oom_config_screen_on}" in
		verylight)
			echo "9533,12938,16683,25195,28940,34048" > /sys/module/lowmemorykiller/parameters/minfree;
			echo "64" > /sys/module/lowmemorykiller/parameters/cost;
		;;
		light)
			echo "11110,15078,19443,29363,33728,39680" > /sys/module/lowmemorykiller/parameters/minfree;
			echo "48" > /sys/module/lowmemorykiller/parameters/cost;
		;;
		medium)
			echo "13332,18094,23331,35235,40473,47616" > /sys/module/lowmemorykiller/parameters/minfree;
			echo "32" > /sys/module/lowmemorykiller/parameters/cost;
		;;
		aggressive)
			echo "16629,22568,29102,43950,50483,59392" > /sys/module/lowmemorykiller/parameters/minfree;
			echo "16" > /sys/module/lowmemorykiller/parameters/cost;
		;;
		exterminate)
			echo "22220,30156,38886,58726,67456,79360" > /sys/module/lowmemorykiller/parameters/minfree;
			echo "8" > /sys/module/lowmemorykiller/parameters/cost;
		;;
		*)
			oom_config_screen_on=default;
		;;
	esac;
fi;
