#!/sbin/busybox sh

# $1 - "sync_threshold"
# $2 - value=
# Created By Dorimanx

if [ "a$2" != "a" ]; then
	sync_threshold=$2;

	echo "sync_threshold" > /sys/module/cpu_boost/parameters/sync_threshold;

fi;

echo ${sync_threshold};
