#!/sbin/busybox sh

# $1 - "uksm_gov_on"
# $2 - value=
# Created By Dorimanx

if [ "a$2" != "a" ]; then
	uksm_gov_on=$2;

case "${uksm_gov_on}" in
	full)
		echo "performance" > /sys/kernel/mm/uksm/cpu_governor;
	;;
	medium)
		echo "balanced" > /sys/kernel/mm/uksm/cpu_governor;
	;;
	low)
		echo "conservative" > /sys/kernel/mm/uksm/cpu_governor;
	;;
	quiet)
		echo "battery" > /sys/kernel/mm/uksm/cpu_governor;
	;;
	*)
		uksm_gov_on=performance;
	;;
	esac;
fi;

echo ${uksm_gov_on};
