#!/sbin/busybox sh
# memory process reclaim script, made by Dorimanx

(
	PROFILE=$(cat /data/.gabriel/.active.profile);
	. /data/.gabriel/${PROFILE}.profile;

	if [ ! -f /system/xbin/su ]; then
		exit 1;
	fi;

	if [ "$cortexbrain_process_reclaim" == "on" ]; then
		while true; do

#		sleep ${1:-21600};

		defhrs=${1:-6};
		secs=$((defhrs*3600));
		sleep $secs;

		for i in $(ls /proc/ | grep -E '^[0-9]+'); do
			if [ "$i" -ge "1500" ] && [ -f /proc/$i/reclaim ]; then
				su -c echo "all" > /proc/$i/reclaim;
			fi;
		done;
		date +%H:%M-%D > /data/.gabriel/logs/mem-process-reclaim;
		echo "Done! Ram Reclaimed." >> /data/.gabriel/logs/mem-process-reclaim;
		sleep 60;
		done;
	fi;
)&
