#!/sbin/busybox sh

(
	BB=/sbin/busybox
	PROFILE=$(cat /data/.gabriel/.active.profile);
	. /data/.gabriel/${PROFILE}.profile;

	if [ "$cortexbrain_trim" == "on" ]; then

	# change mode for /tmp/
	ROOTFS_MOUNT=$(mount | grep rootfs | cut -c26-27 | grep -c rw)
	if [ "$ROOTFS_MOUNT" -eq "0" ]; then
		mount -o remount,rw /;
	fi;
	chmod -R 777 /tmp/;



	if [ "$cortexbrain_trim" == "on" ]; then
		SCREEN_WAS_OFF=0;
		SYSTEM_CHECK=$($BB blkid /dev/block/platform/msm_sdcc.1/by-name/system | $BB grep "f2fs" | $BB wc -l)
		DATA_CHECK=$($BB blkid /dev/block/platform/msm_sdcc.1/by-name/data | $BB grep "f2fs" | $BB wc -l)
		CACHE_CHECK=$($BB blkid /dev/block/platform/msm_sdcc.1/by-name/cache | $BB grep "f2fs" | $BB wc -l)

		if [ "$SYSTEM_CHECK" -eq "0" ] || [ "$DATA_CHECK" -eq "0" ] || [ "$CACHE_CHECK" -eq "0" ]; then
			if [ "$(dumpsys power | grep mWakefulness= | grep -oE '(Awake|Asleep)')" == "Asleep" ] ; then
				input keyevent 26 # wakeup
				SCREEN_WAS_OFF=1;
			fi;
		fi;

		while true; do

# can get two argument for hour & minute

		hrs=${1:-22}
		min=${2:-00}
		while [ $(date +%H:%M) != $hrs":"$min ]; do sleep 1; done


#		while [ $(date +%H:%M) != "22:00" ]; do sleep 1; done
echo "passed sleep" >> /data/.gabriel/logs/debugging_fstrim;

		if [ "$SYSTEM_CHECK" -eq "0" ]; then
			$BB fstrim /system
		fi;
		if [ "$DATA_CHECK" -eq "0" ]; then
			$BB fstrim /data
		fi;
		if [ "$CACHE_CHECK" -eq "0" ]; then
			$BB fstrim /cache
		fi;
		date +%H:%M-%D > /data/.gabriel/logs/fstrim;
		echo "FS Trimmed." >> /data/.gabriel/logs/fstrim;
		sync;
		sleep 60;
		if [ "$SCREEN_WAS_OFF" -eq "1" ]; then
			if [ "$(dumpsys power | grep mWakefulness= | grep -oE '(Awake|Asleep)')" == "Awake" ] ; then
				input keyevent 26 # sleep
			fi;
		fi;
		done;
	fi;
	fi;
)&
